spring.application.name=backend
server.port=8080

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:localkart
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# CORS Configuration (optional, usually handled in controller)
# spring.mvc.cors.allowed-origins=*
